version: '3.8'

services:
  personal-website:
    build: .
    container_name: personal-website
    restart: unless-stopped
    ports:
      - "18475:80"  # Unique external port for Nginx Proxy Manager
    environment:
      - NODE_ENV=production