services:
  personal-website:
    build: .
    container_name: personal-website
    restart: unless-stopped
    ports:
      - "18475:8080"  # Unique external port for Nginx Proxy Manager
    environment:
      - NODE_ENV=production
    network_mode: bridge

