#!/bin/bash

# Quick access information for the personal website

echo "🌐 Personal Website Access Information"
echo "====================================="
echo ""
echo "The website is deployed to your Unraid server on port 18475."
echo ""
echo "To access it, you need to use your Unraid server's IP address:"
echo ""
echo "  http://<YOUR-UNRAID-IP>:18475"
echo ""
echo "For example:"
echo "  http://192.168.1.100:18475  (replace with your actual Unraid IP)"
echo "  http://unraid.local:18475   (if you have local DNS)"
echo ""
echo "❌ NOT accessible at:"
echo "  http://localhost:18475      (this only works ON the Unraid server itself)"
echo ""
echo "To find your Unraid IP address:"
echo "1. Log into Unraid web interface"
echo "2. Check Dashboard or Settings > Network Settings"
echo "3. Or from your Mac: ping unraid.local (if mDNS is working)"
echo ""
echo "If you still can't access it:"
echo "1. SSH into your Unraid server"
echo "2. Run: docker ps | grep personal-website"
echo "3. Check if the container is running"
echo "4. Run: docker logs personal-website"
echo "5. Check for any errors"