#!/bin/bash

echo "🔍 Workflow Failure Debug Guide"
echo "==============================="
echo ""
echo "Since the workflow failed, here are common issues and how to check them:"
echo ""
echo "1. Check GitHub Actions logs:"
echo "   - Go to: https://github.com/zachyzissou/personal-website/actions"
echo "   - Click on the failed workflow run"
echo "   - Look for the specific step that failed"
echo ""
echo "2. Common failure points:"
echo ""
echo "   a) Docker Compose syntax error:"
echo "      - The deploy script runs 'docker-compose down' and 'docker-compose up'"
echo "      - If docker-compose.yml has syntax errors, it will fail here"
echo ""
echo "   b) Port already in use:"
echo "      - Another container might be using port 18475"
echo "      - SSH to Unraid and run: docker ps | grep 18475"
echo ""
echo "   c) Build failures:"
echo "      - Check if 'npm run build' is failing"
echo "      - Look for TypeScript or Astro errors"
echo ""
echo "   d) Container name conflict:"
echo "      - The deploy script runs: docker rm -f personal-website"
echo "      - But if permissions are wrong, this might fail"
echo ""
echo "3. To manually check on Unraid:"
echo "   ssh root@<unraid-ip>"
echo "   cd /deploy-target"
echo "   docker-compose config  # Validates the compose file"
echo "   docker ps -a | grep personal-website"
echo "   docker logs personal-website"
echo ""
echo "4. Quick fixes to try:"
echo "   # On Unraid server:"
echo "   cd /deploy-target"
echo "   docker-compose down"
echo "   docker rm -f personal-website || true"
echo "   docker-compose up -d --build"
echo ""
echo "5. If the compose file is the issue:"
echo "   - We just updated it to use version 3.8"
echo "   - Uses a custom network: personal-website-net"
echo "   - This should be compatible with most Docker versions"