name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore: [ main ]

jobs:
  lint-and-test:
    runs-on: [self-hosted, LinuxX64, personal-website]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: |
        if npm run lint --if-present; then
          echo "✅ Linting passed"
        else
          echo "⚠️ No linting configured"
        fi
      continue-on-error: true
      
    - name: Run type checking
      run: |
        if npm run type-check --if-present; then
          echo "✅ Type checking passed"
        else
          echo "⚠️ No type checking configured"
        fi
      continue-on-error: true
      
    - name: Build website
      run: npm run build
      
    - name: Run tests
      run: |
        if npm run test --if-present; then
          echo "✅ Tests passed"
        else
          echo "⚠️ No tests configured"
        fi
      continue-on-error: true

  preview-build:
    runs-on: [self-hosted, LinuxX64, personal-website]
    needs: lint-and-test
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build preview
      run: npm run build
      
    - name: Generate preview info
      run: |
        echo "🚀 Preview build completed for PR #${{ github.event.number }}"
        echo "Branch: ${{ github.head_ref }}"
        echo "Commit: ${{ github.sha }}"